USE [BD2]

--VALIDAR NO NUMEROS EN NOMBRE DE USUARIOS
ALTER TABLE practica1.Usuarios WITH NOCHECK
ADD CONSTRAINT CK_first_name_only_letters CHECK (Firstname NOT LIKE '%[0-9]%');

--VALIDAR NO NUMEROS EN APELLIDO DE USUARIOS
ALTER TABLE practica1.Usuarios WITH NOCHECK
ADD CONSTRAINT CK_last_name_only_letters CHECK (Lastname NOT LIKE '%[0-9]%');

--VALIDAR NO NUMEROS EN NOMBRE DE CURSO
ALTER TABLE practica1.Course WITH NOCHECK
ADD CONSTRAINT CK_name_course_only_letters CHECK (Name NOT LIKE '%[0-9]%');

--VALIDAR SOLO NUMEROS EN CÓDIGO DE CURSO
ALTER TABLE practica1.Course WITH NOCHECK
ADD CONSTRAINT CK_CodCourse_only_numbers CHECK (CodCourse LIKE '%[0-9]%');

--VER REGISTROS CON PROBLEMA
DBCC CHECKCONSTRAINTS WITH ALL_CONSTRAINTS;

--ELIMINAR
ALTER TABLE practica1.Course
DROP CONSTRAINT CK_CodCourse_only_numbers;